version: '3'
services:

  mariadb:
    image: "mariadb:10.5.8"
    ports:
      - "0.0.0.0:3307:3306"
    expose:
      - 3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-flush-log-at-trx-commit=0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  web:
    build: .
    depends_on:
        - mariadb
    ports:
      - "0.0.0.0:3000:3000"
    env_file: ".env"
    restart: always
    environment:
      TYPEORM_CONNECTION: "mariadb"
      TYPEORM_HOST: mariadb
      TYPEORM_USERNAME: "test"
      TYPEORM_PASSWORD: "test"
      TYPEORM_DATABASE: "test"
      TYPEORM_PORT: 3306
      TYPEORM_SYNCHRONIZE: 1

