version: '3'
services:

  mariadb:
    image: "mariadb:10.1.16"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  web:
    build: .
    depends_on:
        - mariadb
    ports:
      - "0.0.0.0:3000:3000"
      - "0.0.0.0:5858:5858"
    env_file: ".env"
    restart: always
    environment:
      TYPEORM_CONNECTION: "mariadb"
      TYPEORM_HOST: mariadb
      TYPEORM_USERNAME: "test"
      TYPEORM_PASSWORD: "test"
      TYPEORM_DATABASE: "test"
      TYPEORM_PORT: 3306
      TYPEORM_SYNCHRONIZE: 1
      TYPEORM_LOGGING: 1
      TYPEORM_ENTITIES: "build/entity/**/*.js"
      TYPEORM_MIGRATIONS: "build/migration/**/*.js"
      TYPEORM_SUBSCRIBERS: "build/subscriber/**/*.js"
      TYPEORM_ENTITIES_DIR: "build/entity"
      TYPEORM_MIGRATIONS_DIR: "build/migration"
      TYPEORM_SUBSCRIBERS_DIR: "build/subscriber"
