version: '3'
services:

  postgres:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - '${TYPEORM_PORT}:${TYPEORM_PORT}'
    expose:
      - ${TYPEORM_PORT}
    command: -p ${TYPEORM_PORT}
    restart: always
  redis:
    image: "redis:alpine"
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    expose:
      - ${REDIS_PORT}

  web:
    build: .
    depends_on:
        - postgres
    ports:
      - "0.0.0.0:3001:3001"
    env_file: ".env"
    restart: always
    volumes:
      - ./build:/server/build
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: ${REDIS_PORT}
      TYPEORM_CONNECTION: "postgres"
      TYPEORM_HOST: postgres
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_DATABASE: ${TYPEORM_DATABASE}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_SYNCHRONIZE: 1

