version: '3'
services:

  mariadb:
    image: "mariadb:10.1.16"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    volumes:
      - mysql-volume:/var/lib/mysql

  web:
    build: .
    depends_on:
        - mariadb
    ports:
      - "0.0.0.0:3000:3000"
      - "0.0.0.0:5858:5858"
    env_file: ".env"
    restart: always
    environment:
      TYPEORM_HOST: mariadb

volumes:
  mysql-volume:
